ENV: "debug"
BASE_URL:
HOST: "127.0.0.1"
PORT: "8083"

POSTGRES_USERNAME: "postgres"
POSTGRES_PASSWORD: "postgres"
POSTGRES_HOST: "127.0.0.1"
POSTGRES_PORT: "5432"
POSTGRES_DATABASE: "pegawai"

SMTP_HOST:
SMTP_PORT:
SMTP_PASSWORD:
SMTP_USERNAME:
SMTP_SENDER:

MINIO_ENDPOINT:
MINIO_USERNAME:
MINIO_PASSWORD:
MINIO_SSL:
MINIO_BUCKET:
CDN_BASE_URL:
FORCE_LOCAL_STORAGE: true

REDIS_HOST: "127.0.0.1"
REDIS_PORT: "6379"
REDIS_USERNAME:
REDIS_PASSWORD:

USE_OLTP_GRAFANA: false
OTEL_SERVICE_NAME: "my-awesome-service"
OTEL_INSTANCE_ID: "instance-1"

OTLP_TRACE_HTTP: "localhost:4318"
OTLP_TRACE_USE_HTTPS: false

OTLP_METRIC_HTTP: "localhost:4318"
OTLP_METRIC_USE_HTTPS: false
OTEL_METRIC_EXPORT_INTERVAL_IN_S: 5

OTLP_LOG_HTTP: "localhost:4318"
OTLP_LOG_USE_HTTPS: false
